In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Load dataset
data = pd.read_csv('Books_data.csv')
data.head()

,Book Title,Author,Category,Price (TK),Stock Status,Copies Left,Book Length (Pages),Edition,Publication,Wished Users,Discount Offer,Ratings,Reviews
0,Sapiens A Brief History Of Humankind,Yuval Noah Harari,History and Tradition,"1,258",In Stock,4,498,1st Published,Vintage Books (India),386,Yes,39.0,16.0
1,The Intelligent Investor,Benjamin Graham,"Business, Investment and Economics","1,598",In Stock,6,640,8th Impression,Harpercollins Publishers (India),531,Yes,30.0,25.0
2,Madinah Arabic Reader 1,Dr. V. Abdur Rahim,Islamic Books,528,In Stock,21,80,1st Edition 2011,Goodword Books (India),NaN,Yes,6.0,3.0
3,The Quran,M.A.S. Abdel Haleem (Translator),Islamic Books,950,In Stock,38,512,Reissue Edition,"Oxford University Press, USA",NaN,Yes,19.0,5.0
4,"Let Us C, 19th Edition",Yashavant Kanetkar,Computer Science & Engineering,718,In Stock,18,492,19th Edition,BPB Publications (India),NaN,Yes,3.0,1.0

In [2]:
# Summary statistics
data.describe(include='all')

# Check for missing values
data.isnull().sum()

Book Title              0
Author                  0
Category                0
Price (TK)              0
Stock Status            0
Copies Left             0
Book Length (Pages)     0
Edition                 0
Publication             1
Wished Users           21
Discount Offer          0
Ratings                 2
Reviews                 2
dtype: int64

In [5]:
import pandas as pd

# Step 1: Read the CSV file
df = pd.read_csv('Books_data.csv')

# Step 2: Remove the 'Wished Users' column
df = df.drop(columns=['Wished Users'])

# Step 3: Clean the 'Price (TK)' column by removing commas and converting to numeric
df['Price (TK)'] = df['Price (TK)'].replace({',': ''}, regex=True).astype(float)

# Convert 'Copies Left', 'Ratings', 'Reviews' columns to numeric, coerce errors (invalid parsing becomes NaN)
df['Copies Left'] = pd.to_numeric(df['Copies Left'], errors='coerce')
df['Ratings'] = pd.to_numeric(df['Ratings'], errors='coerce')
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

# Step 4: Handle missing values
# Fill missing values in numeric columns with the median of each column (this is just one option)
df['Copies Left'] = df['Copies Left'].fillna(df['Copies Left'].median())
df['Ratings'] = df['Ratings'].fillna(df['Ratings'].median())
df['Reviews'] = df['Reviews'].fillna(df['Reviews'].median())

# Check the cleaned dataframe
print(df.head())

KeyError: 'Ratings'

In [6]:
import pandas as pd

# Step 1: Read the CSV file
df = pd.read_csv('Books_data.csv')

# Step 2: Remove the 'Wished Users' column
df = df.drop(columns=['Wished Users'], errors='ignore')

# Step 3: Print column names to verify the existence of 'Ratings' and other columns
print(df.columns)

# Step 4: Clean the 'Price (TK)' column by removing commas and converting to numeric
df['Price (TK)'] = df['Price (TK)'].replace({',': ''}, regex=True).astype(float)

# Convert 'Copies Left', 'Ratings', 'Reviews' columns to numeric, coerce errors (invalid parsing becomes NaN)
df['Copies Left'] = pd.to_numeric(df['Copies Left'], errors='coerce')

# Check if 'Ratings' and 'Reviews' columns exist, and clean them if they do
if 'Ratings' in df.columns:
    df['Ratings'] = pd.to_numeric(df['Ratings'], errors='coerce')

if 'Reviews' in df.columns:
    df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

# Step 5: Handle missing values
df['Copies Left'] = df['Copies Left'].fillna(df['Copies Left'].median())

# Check the cleaned dataframe
print(df.head())

Index(['Book Title', 'Author', 'Category', 'Price (TK)', 'Stock Status',
       'Copies Left', 'Book Length (Pages)', 'Edition', 'Publication',
       'Discount Offer', 'Ratings ', 'Reviews'],
      dtype='object')
                             Book Title                            Author  \
0  Sapiens A Brief History Of Humankind                 Yuval Noah Harari
1              The Intelligent Investor                   Benjamin Graham
2               Madinah Arabic Reader 1                Dr. V. Abdur Rahim
3                             The Quran  M.A.S. Abdel Haleem (Translator)
4                Let Us C, 19th Edition                Yashavant Kanetkar

                              Category  Price (TK) Stock Status  Copies Left  \
0                History and Tradition      1258.0     In Stock          4.0
1   Business, Investment and Economics      1598.0     In Stock          6.0
2                        Islamic Books       528.0     In Stock         21.0
3                        Islamic Books       950.0     In Stock         38.0
4       Computer Science & Engineering       718.0     In Stock         18.0

   Book Length (Pages)           Edition                       Publication  \
0                  498     1st Published             Vintage Books (India)
1                  640    8th Impression  Harpercollins Publishers (India)
2                   80  1st Edition 2011            Goodword Books (India)
3                  512   Reissue Edition      Oxford University Press, USA
4                  492      19th Edition          BPB Publications (India)

  Discount Offer  Ratings   Reviews
0            Yes      39.0     16.0
1            Yes      30.0     25.0
2            Yes       6.0      3.0
3            Yes      19.0      5.0
4            Yes       3.0      1.0